version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030dD
      POSTGRES_DB: avito
    ports:
      - "5436:5432"

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - USER=postgres
      - PASSWORD=102030dD
      - DBNAME=postgres
